airbnb:
  outputs:
    dev:
      type: snowflake
      account: PSBRRAE-LB94283
      user: DBT

      role: TRANSFORM
      private_key_path: ./rsa_key.p8
      private_key_passphrase: q

      database: AIRBNB
      schema: DEV
      threads: 1
      warehouse: COMPUTE_WH
  target: dev
